version: 1.0.{build}
image: Visual Studio Community 2019
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
build_script:
  - dotnet build -c Release
test_script:
  - dotnet teset YumiChanDBCore.xUnit.Tests/YumiChanDBCore.xUnit.Tests.csproj